<?php $stores = Mage::getModel('core/store')->getCollection()->addFieldToFilter('is_active', 1)->addFieldToFilter('store_id', array('neq' => 0)); ?>
<?php if (count($stores) > 1): ?>
    <?php foreach ($stores as $store): ?>
        <?php if ($store->getId() != $this->getCurrentStoreId()): ?>
            <li>
                <a href="<?php echo $store->getCurrentUrl() ?>">
                    <?php echo $store->getName(); ?>
                </a>
            </li>
        <?php endif; ?>
    <?php endforeach; ?>
<?php endif; ?>
