<div id="mini_cart" data-dropdown-content class="f-dropdown content">
    <?php if ($this->getIsNeedToDisplaySideBar()): ?>
        <?php $_cartQty = $this->getSummaryCount() ?>
        <?php if ($_cartQty > 0): ?>
            <div class="summary">
                <?php if ($_cartQty == 1): ?>
                    <p class="amount"><?php echo $this->__('There is <a href="%s">1 item</a> in your cart.', $this->getUrl('checkout/cart')) ?></p>
                <?php else: ?>
                    <p class="amount"><?php echo $this->__('There are <a href="%s">%s items</a> in your cart.', $this->getUrl('checkout/cart'), $_cartQty) ?></p>
                <?php endif ?>
                <p class="subtotal">
                    <?php if ($this->canApplyMsrp()): ?>
                        <span
                            class="map-cart-sidebar-total"><?php echo $this->__('ORDER TOTAL WILL BE DISPLAYED BEFORE YOU SUBMIT THE ORDER'); ?></span>
                    <?php else: ?>
                        <span><?php echo $this->__('Cart Subtotal:') ?></span> <?php echo Mage::helper('checkout')->formatPrice($this->getSubtotal()) ?>
                        <?php if ($_subtotalInclTax = $this->getSubtotalInclTax()): ?>
                            <br/>(<?php echo Mage::helper('checkout')->formatPrice($_subtotalInclTax) ?><?php echo Mage::helper('tax')->getIncExcText(true) ?>)
                        <?php endif; ?>
                    <?php endif; ?>
                </p>
            </div>
        <?php endif ?>
        <?php $_items = $this->getRecentItems() ?>
        <?php if (count($_items)): ?>
            <p class="block-subtitle"><?php echo $this->__('Recently added item(s)') ?></p>
            <fieldset>
                <table id="shopping-cart-table" class="data-table cart-table">
                    <thead>
                    <tr>
                        <th rowspan="<?php echo $mergedCells; ?>" class="a-center"><?php echo $this->__('Qty') ?></th>
                        <th rowspan="<?php echo $mergedCells; ?>"><span
                                class="nobr"><?php echo $this->__('Product Name') ?></span></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($this->getItems() as $_item): ?>
                        <?php echo $this->getItemHtml($_item) ?>
                    <?php endforeach ?>
                    </tbody>
                </table>
                <script type="text/javascript">decorateTable('shopping-cart-table')</script>
            </fieldset>
        <?php else: ?>
            <p class="empty"><?php echo $this->__('You have no items in your shopping cart.') ?></p>
        <?php endif ?>
        <?php if ($_cartQty && $this->isPossibleOnepageCheckout()): ?>
            <div class="actions">
                <?php echo $this->getChildHtml('extra_actions') ?>
                <button type="button tiny"
                        title="<?php echo Mage::helper('core')->quoteEscape($this->__('View Shopping Cart')) ?>" class="button"
                        onclick="setLocation('<?php echo $this->getUrl('checkout/cart') ?>')">
                    <span><span><?php echo $this->__('View Shopping Cart') ?></span></span></button>
            </div>
        <?php endif ?>
    <?php endif; ?>
</div>
