<div class="footer-container">
    <div class="footer">
        <div class="footer_payments">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_payments')->toHtml(); ?>
        </div>
        <div class="footer_shipping">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_shipping')->toHtml(); ?>
        </div>
        <?php echo $this->getChildHtml('footer.newsletter') ?>
        <div class="footer_links">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links')->toHtml(); ?>
        </div>
        <div class="footer_service">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_service')->toHtml(); ?>
            <?php echo $this->getChildHtml('store_switcher') ?>
        </div>
        <div class="footer_quality">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_quality')->toHtml(); ?>
        </div>
        <div class="footer_partner">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_partner')->toHtml(); ?>
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_social')->toHtml(); ?>
        </div>
        <div class="footer_stars">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_stars')->toHtml(); ?>
        </div>
        <div class="footer_manufactures">
            <h2><?php echo $this->__('Unsere starken Gastro-Marken') ?></h2>
            <?php echo $this->getChildHtml('footer.manufacture_list') ?>
        </div>
    </div>
</div>
<div class="copyright-container">
    <div class="notification">
        <p>
            <small>Copyright 2016 <a href="http://www.newgastroline.de" rel="nofollow" target="_blank">New Gastroline
                    GmbH</a> | All Rights Reserved
            </small>
        </p>
    </div>
</div>
<div class="cookie-container">
    <div class="notification">
        <div class="message">
            <p><?php echo $this->__('Wir verwenden Cookies, um Ihnen den bestmöglichen Service zu gewährleisten. Wenn Sie auf der Seite weitersurfen stimmen Sie der Cookie-Nutzung zu.') ?></p>
        </div>
        <div class="actions">
            <div class="button-group">
                <a class="button close-cookie">schließen</a>
                <a class="button hollow"
                   href="<?php echo $this->getUrl('datenschutz') ?>"><?php echo $this->__('Datenschutzerklärung') ?></a>
            </div>
        </div>
    </div>
</div>
<script src="<?php echo $this->getSkinUrl('js/app.js') ?>"></script>