<div class="footer-container">
    <div class="footer-top">
        <a href="#nav-top" id="backtotop">
            <div class="backtotop">
                <span class="navFooterBackToTopText">Zurück zum Seitenanfang</span>
            </div>
        </a>
    </div>
    <div class="footer-middle">
        <div class="content">
            <div class="footer_links">
                <h4>Informationen</h4>
                <ul>
                    <li><a href="<?php echo Mage::getUrl('bestellvorgang'); ?>">Bestellvorgang</a></li>
                    <li><a href="<?php echo Mage::getUrl('lieferung'); ?>">Lieferung</a></li>
                    <li><a href="<?php echo Mage::getUrl('zahlungsarten'); ?>">Zahlungsarten</a></li>
                    <?php if (Mage::app()->getStore()->getId() == '5'): /* B2C */ ?>
                        <li><a href="<?php echo Mage::getUrl('widerrufsbelehrung'); ?>">Widerrufsbelehrung</a></li>
                        <li><a href="<?php echo Mage::getUrl('widerrufsformular'); ?>">Widerrufsformular</a></li>
                        <li><a href="<?php echo Mage::getUrl('streitschlichtung'); ?>">Streitschlichtung</a></li>
                    <?php endif ?>
                    <li><a href="<?php echo Mage::getUrl('batteriegesetz'); ?>">Hinweis nach dem Batteriegesetz</a></li>
                    <li><a href="<?php echo Mage::getUrl('referenzen'); ?>">Referenzen</a></li>
                    <li><a href="<?php echo Mage::getUrl('catalogsearch/advanced'); ?>">Erweiterte Suche</a></li>
                </ul>
            </div>
            <div class="footer_service">
                <h4><?php echo $this->__('Kundenservice') ?></h4>
                <ul>
                    <li><a href="<?php echo Mage::getUrl('contacts'); ?>">Kontakt</a></li>
                    <li><a href="<?php echo Mage::getUrl('leistungen'); ?>">Leistungen</a></li>
                    <li><a href="<?php echo Mage::getUrl('planung'); ?>">Planung</a></li>
                    <li><a href="<?php echo Mage::getUrl('altgeraeteentsorgung'); ?>">Altger&auml;teentsorgung</a></li>
                    <li><a href="<?php echo Mage::getUrl('montage'); ?>">Montage-Service</a></li>
                    <li><a href="<?php echo Mage::getUrl('service'); ?>">Gastro-Service</a></li>
                    <li>
                        <a href="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/fax/faxbestellung.pdf'; ?>"
                           target="_blank" rel="nofollow noopener noreferrer">Faxbestellung</a></li>
                    <?php echo $this->getChildHtml('store_switcher', false) ?>
                </ul>
            </div>
            <div class="footer_manufactures">
                <h4><?php echo $this->__('Unsere starken Gastro-Marken') ?></h4>
                <ul>
                    <li><a href="<?php echo Mage::getUrl('rational'); ?>">Rational Kombidämpfer</a></li>
                    <li><a href="<?php echo Mage::getUrl('winterhalter'); ?>">Winterhalter Spülmaschinen</a></li>
                    <li><a href="<?php echo Mage::getUrl('jura'); ?>">Jura Kaffeevollautomaten</a></li>
                    <li><a href="<?php echo Mage::getUrl('panasonic'); ?>">Panasonic Mikrowellen</a></li>
                    <li><a href="<?php echo Mage::getUrl('unox'); ?>">Unox Kombidämpfer</a></li>
                    <li><a href="<?php echo Mage::getUrl('bartscher'); ?>">Bartscher Gastronomiebedarf</a></li>
                    <li><a href="<?php echo Mage::getUrl('marken'); ?>">weitere Gastro-Marken</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="footer-middle-2">
        <div class="payments">
            <ul>
                <li>
                    <a href="<?php echo Mage::getUrl('zahlungsarten'); ?>#paypal">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/payments/paypal-white.png' ?>"
                         alt="PayPal Logo">
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('zahlungsarten'); ?>#moneyorder">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/payments/vorkasse-white.png' ?>" alt="Vorkasse" />
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('zahlungsarten'); ?>#sofort">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/payments/sofort-white.png' ?>"
                         alt="Sofortüberweisung Logo"/>
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('zahlungsarten'); ?>#invoice">
                        <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/payments/rechnung-white.png' ?>" alt="Rechnung" />
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('zahlungsarten'); ?>#amazon">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA) . 'wysiwyg/payments/amazon-payments-white.png' ?>"
                         alt="Amazon payments"/>
                    </a>
                </li>
                <li>
                    <a href="<?php echo Mage::getUrl('zahlungsarten'); ?>#finanz">
                    <img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'wysiwyg/payments/finanz-white.png' ?>" alt="Finanzierung" />
                    </a>
                </li>
            </ul>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="org">
            <ul>
                <li><a href="<?php echo Mage::getUrl('agb'); ?>">AGB</a></li>
                <li><a href="<?php echo Mage::getUrl('impressum'); ?>">Impressum</a></li>
                <li><a href="<?php echo Mage::getUrl('datenschutz'); ?>">Datenschutz</a></li>
            </ul>
        </div>
        <div class="social">
            <ul>
                <li><a href="https://facebook.com/gastrodax/" target="_blank" rel="nofollow noopener noreferrer"><i
                                class="fa fa-facebook-square"
                                aria-hidden="true"></i></a></li>
                <li><a href="https://plus.google.com/+gastrodax" target="_blank" rel="nofollow noopener noreferrer"><i
                                class="fa fa-google-plus-square"
                                aria-hidden="true"></i></a></li>
                <li><a href="https://www.youtube.com/channel/UCTr6z7_W4adeggGR1Sa717g" target="_blank"
                       rel="nofollow noopener noreferrerr"><i
                                class="fa fa-youtube-square" aria-hidden="true"></i></a></li>
                <li><a href="https://twitter.com/gastrodax" target="_blank" rel="nofollow noopener noreferrer"><i
                                class="fa fa-twitter-square"
                                aria-hidden="true"></i></a></li>
            </ul>
        </div>
    </div>
</div>
<div class="cookie-container">
    <div class="message">
        <p><?php echo $this->__('Wir verwenden Cookies, um Ihnen den bestmöglichen Service zu gewährleisten. Wenn Sie auf der Seite weitersurfen stimmen Sie der Cookie-Nutzung zu.') ?></p>
    </div>
    <div class="actions">
        <div class="button-group">
            <a class="button close-cookie">schließen</a>
            <a class="button hollow"
               href="<?php echo $this->getUrl('datenschutz') ?>"><?php echo $this->__('Datenschutzerklärung') ?></a>
        </div>
    </div>
</div>