<div id="billing-please-wait" class="please-wait" style="display:none">
    <div class="centered">
        <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw margin-bottom"></i>
    </div>
</div>
<form id="co-billing-form" data-abide novalidate>
    <?php if ($this->customerHasAddresses()): ?>
        <div class="billing-address-select-field" id="billing-address-select">
            <label>
                <?php echo $this->__('Select a billing address from your address book or enter a new address.') ?>
            </label>
            <div class="input-box">
                <?php echo $this->getAddressesHtmlSelect('billing') ?>
            </div>
        </div>
    <?php endif; ?>
    <div id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
        <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>"
               id="billing:address_id"/>
        <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
        <?php if (Mage::app()->getStore()->getId() == '4') { ?>
            <div class="osc-double-fields">
                <div class="company-field">
                    <label for="billing:company"><?php echo $this->__('Company') ?>
                        <small><?php echo $this->__('required') ?></small>
                        <input type="text" id="billing:company" name="billing[company]"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
                               title="<?php echo $this->__('Company') ?>" required pattern="text"/>
                        <span class="form-error"><?php echo $this->__('Please enter your company.') ?></span>
                    </label>
                </div>
                <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <div class="vat-field">
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?>
                            <input type="text" id="billing:vat_id" name="billing[vat_id]"
                                   value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>"
                                   title="<?php echo $this->__('VAT Number') ?>"/>
                        </label>
                    </div>
                <?php endif; ?>
            </div>
        <?php } ?>
        <div class="osc-double-fields">
            <div class="email-field">
                <label for="billing:email"><?php echo $this->__('Email Address') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="email" name="billing[email]" id="billing:email" value="<?php
                    if ($this->isCustomerLoggedIn()) {
                        $email = $this->getCustomer()->getEmail();
                        echo $this->escapeHtml($email);
                    } else {
                        echo $this->escapeHtml($this->getAddress()->getEmail());
                    }
                    ?>" title="<?php echo $this->__('Email Address') ?>"
                        <?php if ($this->isCustomerLoggedIn()) : ?> disabled="disabled" <?php else: ?>required<?php endif; ?>/>
                    <span class="form-error"><?php echo $this->__('Please enter your email.') ?></span>
                </label>
            </div>
            <?php $streetValidationClass = $this->helper('customer/address')->getAttributeValidationClass('street'); ?>
            <div class="street-field">
                <label for="billing:street1"><?php echo $this->__('Address') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]"
                           id="billing:street1"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                           required pattern="text"/>
                    <span class="form-error"><?php echo $this->__('Please enter the street.') ?></span>
                </label>
            </div>
        </div>
        <div class="osc-double-fields">
            <div class="postcode-field">
                <label for="billing:postcode"><?php echo $this->__('Zip/Postal Code') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]"
                           id="billing:postcode"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                           required pattern="text"/>
                    <span class="form-error"><?php echo $this->__('Please enter the zip/postal code.') ?></span>
                </label>
            </div>
            <div class="city-field">
                <label for="billing:city"><?php echo $this->__('City') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" id="billing:city"
                           required pattern="text"/>
                    <span class="form-error"><?php echo $this->__('Please enter the city.') ?></span>
                </label>
            </div>
        </div>
        <div class="country-field">
            <label for="billing:country_id"><?php echo $this->__('Country') ?>
                <small><?php echo $this->__('required') ?></small>
                <?php echo $this->getCountryHtmlSelect('billing') ?>
                <span class="form-error"><?php echo $this->__('Please enter the country.') ?></span>
            </label>
        </div>
        <div class="region-field">
            <label for="billing:region_id"><?php echo $this->__('State/Province') ?>
                <small><?php echo $this->__('required') ?></small>
                <select
                    id="billing:region_id"
                    name="billing[region_id]"
                    title="<?php echo $this->__('State/Province') ?>"
                    class="validate-select"
                    style="display:none;">
                    <option
                        value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                    //<![CDATA[
                    $('billing:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
                    //]]>
                </script>
                <input
                    type="text"
                    id="billing:region"
                    name="billing[region]"
                    value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                    title="<?php echo $this->__('State/Province') ?>"
                    class="input-text <?php echo $this->helper('customer/address')->getAttributeValidationClass('region') ?>"
                    style="display:none;"/>
                <span class="form-error"><?php echo $this->__('Please enter the state/province.') ?></span>
            </label>
        </div>
        <div class="osc-double-fields">
            <div class="telephone-field">
                <label for="billing:telephone"><?php echo $this->__('Telephone') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="text" name="billing[telephone]"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
                           title="<?php echo $this->__('Telephone') ?>" id="billing:telephone" required pattern="text"/>
                    <span class="form-error"><?php echo $this->__('Please enter the telephone number.') ?></span>
                </label>
            </div>
            <div class="fax-field">
                <label for="billing:fax"><?php echo $this->__('Fax') ?>
                    <input type="text" name="billing[fax]"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
                           title="<?php echo $this->__('Fax') ?>" id="billing:fax" pattern="text"/>
                </label>
            </div>
        </div>
        <?php if (!$this->isCustomerLoggedIn()): ?>
            <?php $dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php $gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($dob->isEnabled() || $gender->isEnabled()): ?>
                <div class="fields">
                    <?php if ($dob->isEnabled()): ?>

                        <?php
                        echo $dob->setDate($this->getQuote()->getCustomerDob())
                            ->setFieldIdFormat('billing:%s')
                            ->setFieldNameFormat('billing[%s]')
                            ->toHtml() ?>

                    <?php endif; ?>
                    <?php if ($gender->isEnabled()): ?>

                        <?php echo $gender->setGender($this->getQuote()->getCustomerGender())
                            ->setFieldIdFormat('billing:%s')
                            ->setFieldNameFormat('billing[%s]')
                            ->toHtml() ?>

                    <?php endif ?>
                </div>
            <?php endif ?>
            <?php if ($this->isTaxvatEnabled()): ?>
                <?php echo $this->getTaxvatHtml() ?>
            <?php endif; ?>
            <div class="fields" id="register-customer-password" style="display: none">
                <div class="password-field">
                    <label for="billing:customer_password"><?php echo $this->__('Password') ?>
                        <small><?php echo $this->__('required') ?></small>
                        <input type="password" name="billing[customer_password]" id="billing:customer_password"
                               title="<?php echo $this->__('Password') ?>" autocomplete="off" required/>
                        <span class="form-error"><?php echo $this->__('Please enter your password.') ?></span>
                    </label>
                </div>
                <div class="password-confirmation-field">
                    <label for="billing:confirm_password"><?php echo $this->__('Confirm Password') ?>
                        <small><?php echo $this->__('required') ?></small>
                        <input type="password" name="billing[confirm_password]"
                               title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password"
                               autocomplete="off" required data-equalto="billing:customer_password" required pattern="text"/>
                        <span class="form-error"><?php echo $this->__('Please make sure your passwords match.') ?></span>
                    </label>
                </div>
            </div>
            <?php echo $this->getChildHtml('persistent.remember.me'); ?>
        <?php endif; ?>
        <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
            <div class="address-book-field">
                <input type="checkbox" name="billing[save_in_address_book]" value="1"
                       title="<?php echo $this->__('Save in address book') ?>" id="billing:save_in_address_book"
                       onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()): ?> checked="checked"<?php endif; ?>/>
                <label for="billing:save_in_address_book">
                    <?php echo $this->__('Save in address book') ?>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="billing[save_in_address_book]" value="1"/>
        <?php endif; ?>
        <?php echo $this->getChildHtml('form.additional.info'); ?>
        <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
    </div>
    <?php if ($this->canShip()): ?>
        <div class="use-for-shipping-field">
            <label><?php echo $this->__('Please select a option.') ?>
                <small><?php echo $this->__('required') ?></small>
            </label>
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes"
                   value="1"<?php if ($this->isUseBillingAddressForShipping()) { ?> checked="checked"<?php } ?>
                   title="<?php echo $this->__('Ship to this address') ?>"
                   onclick="$('shipping:same_as_billing').checked = true;shiptodifferentaddress();"/>
            <label for="billing:use_for_shipping_yes">
                <?php echo $this->__('Ship to this address') ?>
            </label>
            <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no"
                   value="0"<?php if (!$this->isUseBillingAddressForShipping()) { ?> checked="checked"<?php } ?>
                   title="<?php echo $this->__('Ship to different address') ?>"
                   onclick="$('shipping:same_as_billing').checked = false;shiptodifferentaddress(1);"/>
            <label for="billing:use_for_shipping_no">
                <?php echo $this->__('Ship to different address') ?>
            </label>
        </div>
    <?php endif; ?>
    <?php if (!$this->canShip()): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1"/>
    <?php endif; ?>
</form>
<script type="text/javascript">
    //<![CDATA[
    //billingForm.setElementsRelation('billing:country_id', 'billing:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    // $('billing-address-select') && billing.newAddress(!$('billing-address-select').value);
    var billingRegionUpdater = new RegionUpdater('billing:country_id', 'billing:region', 'billing:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'billing:postcode');
    if ($('onepage-guest-register-button')) {
        Event.observe($('onepage-guest-register-button'), 'click', function (event) {
            var billingRememberMe = $('co-billing-form').select('#remember-me-box');
            if (billingRememberMe.length > 0) {
                if ($('login:guest') && $('login:guest').checked) {
                    billingRememberMe[0].hide();
                } else if ($('login:register') && ($('login:register').checked || $('login:register').type == 'hidden')) {
                    billingRememberMe[0].show();
                }
            }
        });
    }
    //]]>
</script>
