<div id="checkout_method-please-wait" class="step-please-wait" style="display:none">
    <div class="centered">
        <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw margin-bottom"></i>
    </div>
</div>
<div class="onestep-step">
    <div class="login-method">
        <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
        <h3><?php if ($this->getQuote()->isAllowedGuestCheckout()) : ?>
                <?php echo $this->__('Checkout as a Guest or Register') ?>
            <?php else: ?><?php echo $this->__('Register to Create an Account') ?>
            <?php endif; ?></h3>
        <form id="co-login-form" data-abide novalidate>
            <div data-abide-error style="display: none;">
                <label class="is-invalid-label"><?php echo $this->__('Please select a option.') ?></label>
            </div>
            <?php if ($this->getQuote()->isAllowedGuestCheckout()) : ?>
                <input type="radio" name="checkout_method" id="login:guest" value="guest"
                    <?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_GUEST) : ?>
                        checked="checked"
                    <?php endif; ?>
                       required/>
                <label for="login:guest">
                    <?php echo $this->__('Checkout as Guest') ?>
                </label>
            <?php endif; ?>
            <input type="radio" name="checkout_method" id="login:register" value="register"
                <?php if ($this->getQuote()->getCheckoutMethod() == Mage_Checkout_Model_Type_Onepage::METHOD_REGISTER
                    || !$this->getQuote()->isAllowedGuestCheckout()
                ) : ?>
                    checked="checked"
                <?php endif ?>
                   required/>
            <label for="login:register">
                <?php echo $this->__('Register') ?>
            </label>
        </form>
    </div>
    <div class="login-method">
        <h3><?php echo $this->__('Registered Customers') ?></h3>
        <label><?php echo $this->__('If you have an account with us, please log in.') ?></label>
        <a href="<?php echo $this->getUrl('customer/account/login') ?>" class="button"><?php echo $this->__('Login') ?></a>
    </div>
</div>
