<div class="page-title">
    <h1><?php echo $this->__('Checkout') ?></h1>
</div>
<div class="osc-column-wrapper">
    <div id="osc-column-up" class="osc-column up"></div>
    <div id="osc-column-left" class="osc-column left"></div>
    <div id="osc-column-center" class="osc-column center"></div>
    <div id="osc-column-right" class="osc-column right"></div>
    <div id="osc-column-bottom" class="osc-column bottom"></div>
</div>
<div id="checkoutStepsPreload">
    <?php
    $i = 0;
    foreach ($this->getSteps() as $stepId => $stepInfo): ?>
        <?php if (!$this->getChild($stepId) || !$this->getChild($stepId)->isShow()): continue; endif;
        $i++ ?>
        <div id="osc-<?php echo $stepId ?>" class="section<?php echo !empty($stepInfo['complete']) ? ' saved' : '' ?>">
            <div id="checkout-step-<?php echo $stepId ?>" class="step a-item">
                <h2 class="step-title"><?php echo $stepInfo['label'] ?></h2>
                <?php echo $this->getChildHtml($stepId) ?>
            </div>
        </div>
    <?php endforeach ?>
</div>
<script type="text/javascript">
    //<![CDATA[
    var baseUrl = '<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_LINK, true); ?>';
    //]]>
</script>
<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/onestepcheckout/classes/MethodStep.js') ?>"
></script>

<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/onestepcheckout/classes/Checkout.js') ?>"
></script>

<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/onestepcheckout/classes/Login.js') ?>"
></script>

<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/onestepcheckout/classes/Billing.js') ?>"
></script>

<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/onestepcheckout/classes/Shipping.js') ?>"
></script>

<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/onestepcheckout/classes/ShippingMethod.js') ?>"
></script>

<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/onestepcheckout/classes/Payment.js') ?>"
></script>

<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/onestepcheckout/classes/Review.js') ?>"
></script>

<script
    type="text/javascript"
    src="<?php echo $this->getSkinUrl('js/onestepcheckout/onestep.js') ?>"
></script>