<div id="payment_method-please-wait" class="step-please-wait" style="display:none">
    <div class="centered">
        <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw margin-bottom"></i>
    </div>
</div>
<div class="onestep-step">
    <form id="co-payment-form" data-abide novalidate>
        <div id="checkout-load-payment_method">
            <?php echo $this->getChildHtml('methods') ?>
        </div>
        <div id="reload-payment-method">
            <a href="#" id="reload-payment-method-button" class="button split no-pip secondary hollow"><?php echo $this->__('Update payment options'); ?><span><i class="fa fa-refresh"></i></span></a>
        </div>
    </form>
    <div class="tool-tip" id="payment-tool-tip" style="display:none;">
        <div class="btn-close">
            <a href="#" id="payment-tool-tip-close" title="<?php echo $this->__('Close') ?>">
                <?php echo $this->__('Close') ?>
            </a>
        </div>
        <div class="tool-tip-content">
            <img
                src="<?php echo $this->getSkinUrl('images/cvv.gif') ?>"
                alt="<?php echo $this->__('Card Verification Number Visual Reference') ?>"
                title="<?php echo $this->__('Card Verification Number Visual Reference') ?>"/>
        </div>
    </div>
</div>
<script type="text/javascript">
    //<![CDATA[
    function toggleToolTip(event) {
        if ($('payment-tool-tip')) {
            $('payment-tool-tip').setStyle({
                top: (Event.pointerY(event) - 560) + 'px'//,
            })
            $('payment-tool-tip').toggle();
        }
        Event.stop(event);
    }
    if ($('payment-tool-tip-close')) {
        Event.observe($('payment-tool-tip-close'), 'click', toggleToolTip);
    }
    //]]>
</script>
<script type="text/javascript">
    //<![CDATA[
    var currentPaymentMethod = "<?php echo $this->getChild('methods')->getSelectedMethodCode() ?>";
    //]]>
</script>
<div id="payment_method-advice-source" style="display: none">
    <div class="validation-advice advice-required-entry-payment_method" style="display:none">
        <?php echo Mage::helper('checkout')->__('This is a required field.'); ?>
    </div>
</div>