<div id="review-please-wait" class="step-please-wait" style="display:none">
    <div class="centered">
        <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw margin-bottom"></i>
    </div>
</div>
<div class="checkout-review-update-container checkout-clear-both">
    <a href="#_" id="checkout-review-update" class="button split no-pip secondary hollow"><?php echo Mage::helper('checkout')->__('Update order review');?><span><i class="fa fa-refresh"></i></span></a>
</div>
<div class="order-review" id="checkout-load-review">
    <?php echo $this->getChildHtml('info') ?>
</div>

<div id="checkout-review-submit">
    <?php echo $this->getChildHtml('agreements') ?>
    <div class="buttons-set" id="review-buttons-container">
        <p class="f-left">
            <?php echo $this->__('Forgot an Item?') ?> <a href="<?php echo $this->getUrl('checkout/cart') ?>">
                <?php echo $this->__('Edit Your Cart') ?></a>
        </p>
        <?php echo $this->getChildHtml('button') ?>
    </div>
</div>

