<form action="" id="co-shipping-form" data-abide novalidate>
    <?php if ($this->customerHasAddresses()): ?>
        <label>
            <?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?>
        </label>
        <div class="input-box">
            <?php echo $this->getAddressesHtmlSelect('shipping') ?>
        </div>
    <?php endif ?>
    <div id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
        <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>"
               id="shipping:address_id"/>
        <?php echo $this->getLayout()
            ->createBlock('customer/widget_name')
            ->setObject($this->getAddress())
            ->setFieldIdFormat('shipping:%s')
            ->setFieldNameFormat('shipping[%s]')
            ->setFieldParams('onchange="shipping.setSameAsBilling(false)"')
            ->toHtml() ?>
        <?php if (Mage::app()->getStore()->getId() == '4') { ?>
            <div class="osc-double-fields">
                <div class="company-field">
                    <label for="shipping:company"><?php echo $this->__('Company') ?>
                        <small><?php echo $this->__('required') ?></small>
                        <input type="text" id="shipping:company" name="shipping[company]"
                               value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
                               title="<?php echo $this->__('Company') ?>" onchange="shipping.setSameAsBilling(false);" required pattern="text"/>
                        <span class="form-error"><?php echo $this->__('Please enter your company.') ?></span>
                    </label>
                </div>
                <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                    <div class="vat-field">
                        <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?>
                            <input type="text" id="shipping:vat_id" name="shipping[vat_id]"
                                   value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>"
                                   title="<?php echo $this->__('VAT Number'); ?>"/>
                        </label>
                    </div>
                <?php endif; ?>
            </div>
        <?php } ?>
        <div class="street-field">
            <label for="shipping:street1"><?php echo $this->__('Address') ?>
                <small><?php echo $this->__('required') ?></small>
                <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]"
                       id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                       onchange="shipping.setSameAsBilling(false);" required pattern="text"/>
                <span class="form-error"><?php echo $this->__('Please enter the street.') ?></span>
            </label>
        </div>
        <div class="osc-double-fields">
            <div class="postcode-field">
                <label for="shipping:postcode"><?php echo $this->__('Zip/Postal Code') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]"
                           id="shipping:postcode"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                           onchange="shipping.setSameAsBilling(false);" required pattern="text"/>
                    <span class="form-error"><?php echo $this->__('Please enter the zip/postal code.') ?></span>
                </label>
            </div>
            <div class="city-field">
                <label for="shipping:city"><?php echo $this->__('City') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]"
                           value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>" id="shipping:city"
                           onchange="shipping.setSameAsBilling(false);" required pattern="text"/>
                    <span class="form-error"><?php echo $this->__('Please enter the city.') ?></span>
                </label>
            </div>
        </div>
        <div class="country-field">
            <label for="shipping:country_id"><?php echo $this->__('Country') ?>
                <small><?php echo $this->__('required') ?></small>
                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                <span class="form-error"><?php echo $this->__('Please enter the country.') ?></span>
            </label>
        </div>
        <div class="region-field">
            <label for="shipping:region"><?php echo $this->__('State/Province') ?>
                <small><?php echo $this->__('required') ?></small>
                <select
                    id="shipping:region_id"
                    name="shipping[region_id]"
                    title="<?php echo $this->__('State/Province') ?>"
                    style="display:none;">
                    <option
                        value=""><?php echo $this->__('Please select region, state or province') ?></option>
                </select>
                <script type="text/javascript">
                    //<![CDATA[
                    $('shipping:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
                    //]]>
                </script>
                <input
                    type="text"
                    id="shipping:region"
                    name="shipping[region]"
                    value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                    title="<?php echo $this->__('State/Province') ?>"
                    style="display:none;"/>
                <span class="form-error"><?php echo $this->__('Please enter the state/province.') ?></span>
            </label>
        </div>
        <div class="osc-double-fields">
            <div class="telephone-field">
                <label for="shipping:telephone"><?php echo $this->__('Telephone') ?>
                    <small><?php echo $this->__('required') ?></small>
                    <input
                        type="text"
                        name="shipping[telephone]"
                        value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
                        title="<?php echo $this->__('Telephone') ?>"
                        id="shipping:telephone"
                        onchange="shipping.setSameAsBilling(false);" required pattern="text"/>
                    <span class="form-error"><?php echo $this->__('Please enter the telephone number.') ?></span>
                </label>
            </div>
            <div class="fax-field">
                <label for="shipping:fax"><?php echo $this->__('Fax') ?>
                    <input
                        type="text"
                        name="shipping[fax]"
                        value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
                        title="<?php echo $this->__('Fax') ?>"
                        id="shipping:fax"
                        onchange="shipping.setSameAsBilling(false);" pattern="text"/>
                </label>
            </div>
        </div>
        <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
            <div class="address-book-field">
                <input type="checkbox"
                       name="shipping[save_in_address_book]"
                       value="1"
                       title="<?php echo $this->__('Save in address book') ?>"
                       id="shipping:save_in_address_book"
                       onchange="shipping.setSameAsBilling(false);"
                    <?php if ($this->getAddress()->getSaveInAddressBook()): ?> checked="checked"<?php endif; ?>/>
                <label for="shipping:save_in_address_book">
                    <?php echo $this->__('Save in address book') ?>
                </label>
            </div>
        <?php else: ?>
            <input type="hidden" name="shipping[save_in_address_book]" value="1"/>
        <?php endif; ?>
        <div class="same-as-billing-field">
            <input type="checkbox"
                   name="shipping[same_as_billing]"
                   id="shipping:same_as_billing"
                   value="1"<?php if ($this->getAddress()->getSameAsBilling()): ?>
                checked="checked"<?php endif; ?>
                   title="<?php echo $this->__('Use Billing Address') ?>"
                   onclick="shipping.setSameAsBilling(this.checked)"/>
            <label for="shipping:same_as_billing">
                <?php echo $this->__('Use Billing Address') ?>
            </label>
        </div>
    </div>
    <div id="shipping-please-wait" class="please-wait" style="display:none">
        <div class="centered">
            <i class="fa fa-circle-o-notch fa-spin fa-3x fa-fw margin-bottom"></i>
        </div>
    </div>
</form>
<script type="text/javascript">
    //<![CDATA[
    var shippingForm = new VarienForm('co-shipping-form');
    shippingForm.extraChildParams = ' onchange="shipping.setSameAsBilling(false);"';
    //shippingForm.setElementsRelation('shipping:country_id', 'shipping:region', '<?php echo $this->getUrl('directory/json/childRegion') ?>', '<?php echo $this->__('Select State/Province...') ?>');
    //$('shipping-address-select') && shipping.newAddress(!$('shipping-address-select').value);
    var shippingRegionUpdater = new RegionUpdater('shipping:country_id', 'shipping:region', 'shipping:region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'shipping:postcode');
    //]]>
</script>
